version: '3'

services:
  nginx:
    depends_on: [wordpress]
    restart: unless-stopped
    container_name: nginx
    networks: [inception]
    volumes: [wordpress:/var/www/html]
    env_file: .env
    ports: ["443:443"]
    build: 
      context: requirements/nginx
      args:
        CERTS_DIR: ${CERTS_DIR}
        DOMAIN_NAME: ${DOMAIN_NAME}

  wordpress:
    depends_on: [mariadb]
    restart: unless-stopped
    container_name: wordpress
    networks: [inception]
    volumes: [wordpress:/var/www/html]
    env_file: .env
    build: requirements/wordpress

  mariadb:
    restart: unless-stopped
    container_name: mariadb
    networks: [inception]
    volumes: [mariadb:/var/lib/mysql]
    env_file: .env
    build: requirements/mariadb

volumes:
  wordpress:
    name: wordpress
  mariadb:
    name: mariadb

networks:
  inception:
