
services:
  nginx:
    depends_on: [wordpress]
    restart: on-failure
    container_name: nginx
    networks: [inception]
    volumes: [wordpress:/var/www/html]
    env_file: .env
    ports: ["443:443"]
    image: nginx:my-v0.1
    build:
      context: requirements/nginx
      args:
        CERTS_DIR: ${CERTS_DIR}
        DOMAIN_NAME: ${DOMAIN_NAME}

  wordpress:
    depends_on: [mariadb]
    restart: on-failure
    container_name: wordpress
    networks: [inception]
    volumes: [wordpress:/var/www/html]
    env_file: .env
    image: wordpress:my-v0.1
    build:
      context: requirements/wordpress

  mariadb:
    restart: on-failure
    container_name: mariadb
    networks: [inception]
    env_file: .env
    image: mariadb:my-v0.1
    build:
      context: requirements/mariadb
    volumes: [mariadb:/var/lib/mysql]

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      device: /Users/samjaabo/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver_opts:
      device: /Users/samjaabo/data/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception
